spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jumpcloud_bot
    password:
    url: jdbc:postgresql://127.0.0.1:5432/jumpcloudbot
  flyway:
    locations: classpath:db/migration
    schemas: public
    enabled: true
jc-api-key:
slack-signing-secret:
slack-token:
server:
  port: 80
allowed-channels: XYZ, ABC
base-command: /jc
domain: example.com
aws:
  secretName: prd-jumpcloud-slackbot
  region: ap-southeast-1



